### ISSUE TITLE
Render options not being applied

### ISSUE THREAD

**Issue by carlosflorencio** [mrjones2014/mdpreview.nvim#4]
When setting custom options in the `.setup()` function, they are not used when using the commands `:Mdpreview`.

Example config:
```lua
      require('mdpreview').setup {
        renderer = {
          opts = {
            win_opts = {
              wrap = false,
            },
          },
        },
      }
```

When using the command `:Mdpreview`, I was expecting the new window to have the `win_opts` I'm overriding. Instead, the default config with `wrap = true` is being used.

The issue should be [in this line](https://github.com/mrjones2014/mdpreview.nvim/blob/master/lua/mdpreview/views/buffer.lua#L61) where the default opts are being used and not the ones coming from the `.setup()`.

Thanks for the plugin :)

**Comment by mrjones2014** [comment]
Thanks for the bug report!

I haven't tried using it with non-default config, since I don't really even preview Markdown very often. Looking back at the code, I'm pretty sure the `setup()` in `init.lua` is not actually setting user config in the `mdpreview/config.lua` table at all.

Should be an easy fix.

**Comment by carlosflorencio** [comment]
I confirm it's working now, thanks! 💪
